### ISSUE TITLE
RepEx is still on Python 2.7

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex#19]
Therefore cannot work with the current stack.

**Comment by andre-merzky** [comment]
Well, the devel branch is on Py3:
```
$ rs

  python               : 3.7.5
  pythonpath           :
  virtualenv           : /home/merzky/radical/radical.repex/ve3

  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0
  radical.repex        : 0.72.0-v0.72.0-43-gb280266@devel
  radical.saga         : 1.0.0
  radical.utils        : 1.0.0
```

I did not want to push a release before you confirmed it works under py3...

**Comment by SrinivasMushnoori** [comment]
Fair. Currently testing.

**Comment by SrinivasMushnoori** [comment]
I will be testing real MD workloads by end of day today. If those work, I will let you know and you can merge.

**Comment by SrinivasMushnoori** [comment]
Hi, just checking:  I know that in some parts of the code things were missed in the Py3 transition, has there been movement?

**Comment by andre-merzky** [comment]
Hi @SrinivasMushnoori : the code parts are fixed by now (I'll push).  Alas, I am stumbling over locking races in RE again, thus the delay :-(

**Comment by SrinivasMushnoori** [comment]
@andre-merzky Gentle ping. Has there been progress?

**Comment by andre-merzky** [comment]
Hi @SrinivasMushnoori : as always, there are good and bad news.  The devel branch should work as expected now, BUT you will only be able to run small numbers of ensembles, and even those will hang often.  The underlying cause is again  RE (see radical-cybertools/radical.entk/issues/410), the RE folx are looking into it.  I will have to ask you for a bit more patience (again)...  @shantenujha is aware of the state of affairs.

**Comment by SrinivasMushnoori** [comment]
Thanks for the note. 
Let me see if I can set up my science workloads with smaller replica counts. I have been following EnTK #410, so I am aware: please feel free to let me know if you need me to do some testing etc if it helps expedite resolution of the issue.

**Comment by andre-merzky** [comment]
This is resolved now - Python-3 is fully supported.

**Comment by SrinivasMushnoori** [comment]
Closing in that case.
