### ISSUE TITLE
Radical Analytics integration

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex#21]
It's clear that work is currently being done on getting RepEx going on Bridges (which will be the main platform for the project), but could we begin some work on analytics integration? It will not be much longer before Analytics becomes critical for the purpose of performance evaluation results.

**Comment by andre-merzky** [comment]
Analytics is to some extend integrated already: we are able to derive resource utilization, task runtimes etc. from the RP and RE profiles.  Let us know please what additional performance metrics you would be interested in, and we make surer to record the respective profile events.

**Comment by SrinivasMushnoori** [comment]
Correct: but that will not help compute the _RepEx overhead on top of EnTK_ which is something we will be interested in.

**Comment by andre-merzky** [comment]
Then you would need to define what the "repex overhead" is.  For us, an overhead is usually a measure (time or percentage) of one approach compared to another.  The one approach here is repex - what are we comparing against?

**Comment by SrinivasMushnoori** [comment]
My understanding of the matter is as follows:
EnTK calculates its overhead on top of RP (i.e. the overhead incurred by expressing the same workflow in RP vs in EnTK. HTBAC computes overhead on top of EnTK (i.e. the performance differential between HTBAC and expressing the HTBAC overhead in EnTK, as seen [here](https://arxiv.org/pdf/1801.01174.pdf) in figures 4 and 5). 

So to answer your question directly, 

Approach 1: RepEx
Approach 2: Expressing the RepEx workflow in EnTK. 

Does this make sense?

**Comment by andre-merzky** [comment]
RX meanwhile record a number of time stamps, specifically:

```sh
$ grep -r prof.prof src/
src/radical/repex/exchange.py:       self._prof.prof('create', uid=self._uid)
src/radical/repex/replica.py:        self._prof.prof('create', uid=self._rid)
src/radical/repex/replica.py:        self._prof.prof('init', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('add_md_start', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('add_md_stop', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('chk_ex_start', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('chk_ex_stop', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('add_ex_start', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('add_ex_stop', uid=self.rid)
src/radical/repex/replica.py:        self._prof.prof('chk_res_start', uid=self.rid, msg=ret)
src/radical/repex/replica.py:        self._prof.prof('chk_res_stop', uid=self.rid, msg=ret)
```

Those are recorded in `radical.entk.appmanager.0000.prof` in the client sandbox.
