### ISSUE TITLE
MD stage should support pre- and post processing stages

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.repex#22]

**Comment by andre-merzky** [comment]
How would tasks in a pre-stage be different from a task in a normal stage?

**Comment by SrinivasMushnoori** [comment]
Typically, a pre-stage would involve some kind of MD engine specific pre processing: which is most usually single core. Other than that, no real difference. It is important to also note that GROMACS is the only MD engine that really uses this sort of specific preprocessing. So we are dealing with the exception rather than the rule here.

**Comment by andre-merzky** [comment]
If calling the pre/post-stage name makes semantics a bit clearer, then that's ok - but please weigh if adding a concept is worthwhile if the same can be achieved by adding a 'normal' stage with a single-core task...

**Comment by SrinivasMushnoori** [comment]
Fair enough, but there are two things I need to point out here:
1) This is usecase critical unfortunately, and switching to a different MD engine isn't an option at the moment so we are locked to GROMACS
2) While the preprocessing is single core, it is done by invoking the `gmx_mpi`  executable and then supplying it with a single core. I do not know if at the SAGA level there is a distinction there.

**Comment by andre-merzky** [comment]
Oh, please don't get me wrong - the use case needs to be supported of course!  My question is more about naming than anything else: I wonder how a 'pre-stage' differs from a normal 'stage' (a stage always comes before some other stage, or after some other stage)

**Comment by iparask** [comment]
> by adding a 'normal' stage with a single-core task, especially if the concept is rarely used as you seem to suggest...

I see your point. As I understand it, there is the general `md` stage. This is not changed at all and it should not. GROMACS, however, requires pre- and post- processing steps and we thought to add two keys `pre_proc` and `post_proc`. These will then translate to 'normal' stages as you say and added to the workflow.

If the keys do not exist in the workflow definition, then only an md stage will be created. Otherwise, if they exist additional stages will be added to the workflow.

Does it make sense?

**Comment by andre-merzky** [comment]
Thanks both, that helps.  I am not sure I appreciate the overloading of `pre_exec` still (on on the stage level, one on the task level - so you end up having `pre_exec` of `pre_exec`, but I see that it works.  I guess an alternative I could suggest to change the `workload['md']` from a dict to a list of dicts which then translates from a single stage to a set of stages - which might also be a bit more generic if the MD part of the pipeline happens to consist of, say 4 different steps.

**Comment by iparask** [comment]
> I guess an alternative I could suggest to change the `workload['md']` from a dict to a list of dicts which then translates from a single stage to a set of stages - which might also be a bit more generic if the MD part of the pipeline happens to consist of, say 4 different steps.

Exactly!
