### ISSUE TITLE
RepEx forces single core replicas?

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex#24]
I think RepEx uses only one core per replica no matter what. I just noticed this. It didnt matter until now since I was only running short thermodynamic configuration simulations, but I tried running a 2000 cycle production REMD and it seemed to take way too long. I dug into the sandbox and found the task sandbox has the following in the `task.0001.sh` file:
```
# The command to run
prof task_exec_start
mpirun  -np 1  -host r379 -x "LD_LIBRARY_PATH" -x "PATH" -x "PYTHONPATH" -x "OMP_NUM_THREADS" -x "RP_AGENT_ID" -x "RP_GTOD" -x "RP_PILOT_ID" -x "RP_PILOT_STAGING" -x "RP_PROF" -x "RP_SESSION_ID" -x "RP_SPAWNER_ID" -x "RP_TMP" -x "RP_TASK_ID" -x "RP_TASK_NAME" -x "RP_PILOT_SANDBOX" -x "RADICAL_BASE" -x "NODE_LFS_PATH"  gmx_mpi "mdrun" "-s" "sys.tpr" "-deffnm" "sys" "-c" "outcrd.gro" "-e" "sys.edr" "-cpt" "10000000"
RETVAL=$?
prof task_exec_stop
```

Clearly, it's only using one core because of `mpirun -np 1`

I assume this is a quick fix? Pinging @andre-merzky since I am assuming Giannis has left.

**Comment by andre-merzky** [comment]
> I assume this is a quick fix?

I should hope though.

What is the task description you specify for that task?

> I am assuming Giannis has left.

That is correct *sigh*

**Comment by SrinivasMushnoori** [comment]
Here's the input json:

https://github.com/radical-cybertools/radical.repex/blob/user/repex/tests/unittests/test_case/workflow_gromacs.json

**Comment by andre-merzky** [comment]
Thanks @SrinivasMushnoori .  Can you please also provide the output of `radical-stack`?  Thanks!

**Comment by SrinivasMushnoori** [comment]
Oops. My bad.

```
  python               : /home/scm177/Virtual_Envs/repex_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env

  radical.entk         : 1.6.0
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.2-v1.6.2-166-g80f1a23@user-repex
  radical.repex        : 0.72.0-e8871d7@feature-multi_md_steps
  radical.saga         : 1.6.1
  radical.utils        : 1.6.2
```

**Comment by andre-merzky** [comment]
Oh, I don't see that branch `feature/multi_md_steps` in the repo.  Where can I find that?

**Comment by SrinivasMushnoori** [comment]
Ah, I see Giannis merged with `user/repex` before he left. 
https://github.com/radical-cybertools/radical.repex/tree/user/repex

**Comment by SrinivasMushnoori** [comment]
@andre-merzky I just confirmed, this is completely reproducible on the `user/repex` branch.

**Comment by andre-merzky** [comment]
Thanks for confirming that.  I'll likely not manage to dig into it today (too many calls), but will ping back tomorrow.

**Comment by andre-merzky** [comment]
I am afraid I am not able to reproduce the problem.  Using this stack:
```sh
$ rs

  python               : /mnt/home/merzky/radical/radical.repex/ve3/bin/python3
  pythonpath           : 
  version              : 3.8.0
  virtualenv           : /mnt/home/merzky/radical/radical.repex/ve3

  radical.entk         : 1.6.5
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.5-v1.6.5-161-g108f06e8b@user-repex
  radical.repex        : 0.72.0-v0.72.0-65-g3222e61@user-repex
  radical.saga         : 1.6.5
  radical.utils        : 1.6.5
```

I see the expected mix of MPI ranks  with this config file
```sh
$ grep mpirun */*sh | cut -f 2- -d : | sed -e 's/-x [^ ]*//g' | tr -s ' ' | sort | uniq -c
     20 mpirun -np 1 -host localhost /bin/echo "grompp" "-f" "mdin.mdp" "-c" "inpcrd.gro" "-o" "sys.tpr" "-p" "sys.top"
     20 mpirun -np 1 -host localhost echo gmx_mpi "energy" "-f" "sys.edr" "-b" "0.25" < "inp.ener" > "mdinfo"
     20 mpirun -np 4 -host localhost,localhost,localhost,localhost echo gmx_mpi "mdrun" "-s" "sys.tpr" "-deffnm" "sys" "-c" "outcrd.gro" "-e" "sys.edr"
```

(I used `echo` as executable, don't have `mdrun` installed).

Do you have any suggestion on how to proceed?

**Comment by SrinivasMushnoori** [comment]
Let me try with that stack.

**Comment by andre-merzky** [comment]
I still can't reproduce this issue - please reopen if it persists.
