### ISSUE TITLE
Move selection algorithm into new structure

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.repex#3]

**Comment by SrinivasMushnoori** [comment]
Quick question: is the **_selection algorithm_** to be moved out to the new structure, or is it the _exchange method?_ I.e. the `exchange_by_random()` method that is sitting in `bin/radical-repex` currently?

**Comment by SrinivasMushnoori** [comment]
This PR #5 I *think* covers this.

**Comment by andre-merzky** [comment]
This is implemented.
