### ISSUE TITLE
selection algorithm needs to be extracted from bin/radical-repex to allow testing

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex#7]
Currently the selection algorithm (in PR #5 or even [here](https://github.com/radical-cybertools/radical.repex/blob/devel/bin/radical-repex#L77) ) resides in `bin/radical-repex` making it so that importing it is impossible for testing. When that is extracted and placed in a separate file, unit tests may be run on it.

**Comment by andre-merzky** [comment]
This is implemented.
